version: "3.9"
services:
  nginx-service:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx-service/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - pinger-client
      - pinger-api-service
      - pinger-api-db
  pinger-client:
    container_name: pinger-client
    build: ./pinger-client
    volumes:
      - ./pinger-client:/app
      - /app/node_modules
    tty: true
    ports:
      - "8080:8080"
  pinger-api-service:
    container_name: pinger-api-service
    build: ./pinger-api-service
    volumes:
      - ./pinger-api-service:/app
    ports:
      - "5122:5122"
    tty: true
    depends_on:
      - pinger-api-db
  pinger-api-db:
    container_name: pinger-api-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
volumes:
  sqlvolume:

