version: "3.9"
services:
  nginx-service:
    container_name: nginx-service
    build: ./nginx-service
    ports:
      - "80:80"
  pinger-client:
    container_name: pinger-client
    build: ./pinger-client
    volumes:
      - ./pinger-client:/app
      - /app/node_modules
      - /app/packages/**/node_modules
    ports:
      - "3000:3000"
  chat-service:
    container_name: chat-service
    build: ./chat-service/PingerChatHub
    volumes:
      - ./chat-service/PingerChatHub:/app
    ports:
      - "5000:5000"