version: "3.9"
services:
  nginx-service:
    container_name: nginx-service
    build: ./nginx-service
    ports:
      - "80:80"
    depends_on: 
      - pinger-client
      - chat-service
  pinger-client:
    container_name: pinger-client
    build: ./pinger-client
    volumes:
      - ./pinger-client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  chat-service:
    container_name: chat-service
    build: ./chat-service/PingerChatHub
    volumes:
      - ./chat-service/PingerChatHub:/app
    ports:
      - "5000:5000"
  pinger-api-service:
    container_name: pinger-api-service
    build: ./pinger-api-service
    volumes:
      - ./pinger-api-service:/app
    ports:
      - "5122:5122"
  db:
    container_name: pinger-api-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
volumes:
  sqlvolume:

